### ISSUE TITLE
Quick question about hot-reloading

### ISSUE THREAD

**Issue by dupuchba** [ajinasokan/recharge#1]
Hello @ajinasokan ,

Thank's a lot for your video about hot-reloading, it has been really helpful. 
I was wondering what are limitations of hot-reloading like writing new classes or shadowing existing classes. It seems to be explained here :
https://github.com/dart-lang/sdk/wiki/Hot-reload

My goal is to have a "true" REPL experience with being able to redefine classes and import libraries, It has been done 3 years ago here https://medium.com/dartlang/evolving-dart-repl-poc-233440a35e1f

I am really a newbie in Dart and I can't figure out how vm_service works

Thaanks a lot for your time

**Comment by ajinasokan** [comment]
I think that project fully implements it. In theory it should work. If it doesn't that is probably due to some version mismatches of packages or small API changes. I don't know if anything major has changed in terms of the incremental compilation that enables it.

vm_service is just an API to control the Dart VM running. When you compile Dart SDK you can include the server part of this. And when you reload sources it basically replaces all the functions with new ones and continues execution. Rest of the hot reload behaviour can be derived from that. Hot reload can do all the things you mentioned.

The problem is when you have to build REPL. For that you have to use evaluate API, not hot reload. But there are some limitations to the evaluate API. Thats why that dev used cell technique to emulate whatever hot reload does to shadow existing classes.
